name: cw-tiler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - shapely=1.6.4
  - pandas=0.23.4
  - geopandas=0.4.0
  - numpy=1.15.1
  - tqdm
  - rtree=0.8.3
  - pip:
    - rio-tiler
